[features]
seeds = false
skip-lint = false
[programs.localnet]
hello_anchor = "9qykhyh6E1f8bLDqgzcoeD43xb4x8RPs1KuDEvL8rPFp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/nazmul/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
