[package]
name = "solana-movie-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "solana_movie_backend"
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "1.14.13"
